name: Setup Rust (cache & toolchain)
runs:
  using: composite
  steps:
    - name: Install protoc compiler
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install toolchain 1.78.0
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.78.0
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2